### ISSUE TITLE
Failed to activate the escape-utils package

### ISSUE THREAD

**Issue by 47ronin** [BrightIT/escape-utils#6]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [escape-utils](https://github.com/BrightIT/escape-utils) package, v0.5.0

### Stack Trace

Failed to activate the escape-utils package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/macusername/.atom/packages/escape-utils/lib/escape-utils.coffee:10:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:58.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:56.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:56.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:55.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:53.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:53.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:52.2.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:51.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:50.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:44.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
     -0:00.4.0 escape-utils:url-decode (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/Volumes/homeprofile/projects/webapps"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
escape-utils, v0.5.0
file-icons, v1.5.7

# Dev
No dev packages
```

**Comment by SchneiderJonathan** [comment]
same

**Comment by PiotrCzapla** [comment]
version  v0.5.1 was just published that fixes this issue. Thank you for reporting.
